# Generated by Django 3.1.7 on 2021-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='imei_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
